---
- name: Patch systems
  hosts: all
  become: true
  tasks:
    - name: Check operating system
      ansible.builtin.assert:
        that: "ansible_os_family == 'RedHat'"

    - name: Check for updates
      ansible.builtin.yum:
        name: "*"
        state: latest
        exclude: kernel*
      register: updates

    - name: Output updates dictionary
      ansible.builtin.debug:
        msg: "{{ updates }}"
