---
- name: Patch systems
  hosts: all
  become: true
  vars:
    check_only: true

  tasks:
    - name: Check operating system
      ansible.builtin.assert:
        that: "ansible_os_family == 'RedHat'"

    - name: Check for updates
      ansible.builtin.yum:
        name: "*"
        state: latest
        exclude: kernel*
      check_mode: "{{ check_only }}"
      register: updates

    - name: Output updates dictionary
      ansible.builtin.debug:
        msg: "{{ updates }}"

    - name: Apdated package list
      ansible.builtin.debug:
        msg: "{% if item[0] in packages %}{{ packages[item[0]][0].version }}-{{ packages[item[0]][0].release }}.{{ packages[item[0]][0].arch }} >>> {{ item[1] }} {% else %} {{ item[1] }}{% endif %}"
      loop: "{{ updates.changes.updated }}"
      loop_control:
        label: "{{ item[0] }}"
      when: updates.changes is defined
