---
- name: Setup hosts connected to satellite
  hosts: all
  become: true
  gather_facts: false
  vars:
    satellite_pub_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNXlwCwYrd5gvy11dj2O8JmSjjPI+zmufZeCB676FrKiwKS5bzlxrtULOAVtTHy8GnZc4xee6V3bfpmkYuaWO3+pyqYJQmVFhvojs9jGxxGEh6eXykoZ+fICJP9mWw9VsQRSFuThT5NLi82keXP9AeP/I/RO/X0aVAmYaAnRaFhQA2GIMAyKoGQRFCPpuS7NNIAAKdyn9jGfYlwksDmKjT0C0xssRGSpEPDCoBJGE7+VJte5DuQVZpQwRlCArr9zkqx4UzJAUNBToz3p6ss9Vx9E1HAapB1C9Ph9nLX8jBg3rlbBN6bhXoZ6/is+wnQNuiTQWxgt4ds7T1X0IzzyFMuNFDdU+fOVyktwrkkZ6AUDFFUy4S5KexOy3ywOU57X5ghgq1+EQaTQm3AP4PJZfbWzkzWCNFqqNsTdtSjVXaZnDN+oP/6OMRTeTvG0HdR9Y5oZtNchDd2dFV2pbcl0Sy+XToaSZlfAxDIPUgEH84oCJwwJQlADlPhBe661C3/W0= foreman-proxy@satellite.example.com
  tasks:
    - name: Add ssh pub key to ec2-user
      ansible.builtin.authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ satellite_pub_ssh_key }}"
