---
- name: Setup hosts connected to satellite
  hosts: all
  become: true
  gather_facts: false
  vars:
    satellite_pub_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBcgaHAQj2zqjgu8pCvnKiZa4efy8weNusf0AzpvrMDGvy/yF49MaUyuvzgvReRL+9S3IGpntmib0tWR4kWzZ1XQQKgEGVYyS8sigPnUrgoHbBqW4r+et9vjV6mF9ETw9LUC+RwCtWrF3xFFDbLka69lFH1WIATOpCtXvIZ8NFujbe1/va0jbyTh2pNdz5HEIHFPiDZ09OCciuUQ+6yUNjzaucjb2+wRRxqkhVHZ6v2gKVxnGhrX3VZTJW+V9p+705x9w8mwogkLi7WX/pdHPHx6L5KtFOPHBQxI7fdbkdClgX5zxI07MAqquVY6zGLpPnZ/yTfnpO1C2DVYqJdUTU+f6DNSds4GHQEj7wFYLslcmY4E0CAp3F21EClAQDf9pCLDu83EpjgLuu7LWzj+Wb7wgyaQXeusEYCpeI0jnhdydYTe4mw8j89zdT5zjKpIjQecTSV1fTVshG/DbnlOer7bqiu5aw8cUgWRA3RB4AiqHmXDfa5m18H+18cnl00dc= foreman-proxy@satellite.example.com
  tasks:
    - name: Print user name
      ansible.builtin.debug:
        msg: "Adding pub key to user: {{ ansible_user }}"

    - name: Add ssh pub key to ec2-user
      ansible.builtin.authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ satellite_pub_ssh_key }}"
